// BigScreenClient/ClientApp/src/app/card/card.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Animations } from "../animations/animations";
import { Utils } from "../utils";

@Component({
  selector: 'app-card',
  templateUrl: './card.component.html',
  styleUrls: ['./card.component.css'],
  animations: [
    Animations.answer,
    Animations.slideInOut
  ]
})
export class CardComponent implements OnInit {
  @Input() cardMessage: String;
  @Input() answerState: String;
  @Input() movementState: String;

  constructor() { }

  ngOnInit() {
    this.answerState = Utils.STATE_ANSWER_NORMAL;
  }

  @Input() public setAnswerState(answerState: string) {
    this.answerState = answerState;
  }

}

<div class="row text-center h-100 px-5">
    <div [@slideInOut]="movementState" [@answer]="answerState" class="card col-sm-12 shadow">
        <div class="card-body text-center center">
            <h1>{{cardMessage}}</h1>
        </div>
    </div>
</div>

// BigScreenReact/BigScreenReact/ClientApp/src/components/Card.tsx
import React, {useEffect, useState, forwardRef, useImperativeHandle} from 'react'
import { Utils } from '../utils';

interface ICard {
    cardMessage: string;
    answerState: string;
    // movementState: string;
}

interface ICardUseState {
    setCardMessate: React.Dispatch<React.SetStateAction<string>>
    setAnswerState: React.Dispatch<React.SetStateAction<string>>
}

const Card = forwardRef((props: ICard, ref) => {
    
    // useEffect(() => {
    //     props.cardMessage = "Tester"
    //     props.answerState = Utils.STATE_ANSWER_NORMAL
    // }, [])

    return (
        <div className="row text-center h-100 px-5">
            <div className="card col-sm-12 shadow"> 
            {/* [@slideInOut]="movementState" [@answer]="answerState" */}
                <div className="card-body text-center center-my-text">
                    <h1>{props.cardMessage}</h1>
                </div>
            </div>
        </div> 
    )    

});

export default Card;
