// BigScreenAngular/BigScreenClient/ClientApp/src/app/screen-card/screen-card.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { SignalRService } from "../services/signal-r.service";
import { NavigationService } from "../services/navigation.service";
import { Utils } from "../utils";

@Component({
  selector: 'app-screen-card',
  templateUrl: './screen-card.component.html',
  styleUrls: ['./screen-card.component.css']
})
export class ScreenCardComponent implements OnInit {
  
  public groupName: string;

  constructor(public nav: NavigationService, public signalRService: SignalRService) {
    this.signalRService.startConnection(() => {this.init()});
   }

  public currentCount = 0;
  public card1Message = "Welcome!";
  public card2Message = "2";  

  public card1State = Utils.STATE_TRANSITION_ON;
  public card2State = Utils.STATE_TRANSITION_OFF;
  public card1AnswerState = Utils.STATE_ANSWER_NORMAL;
  public card2AnswerState = Utils.STATE_ANSWER_NORMAL;

  
  ngOnInit() {
    this.groupName = this.nav.groupName
  }

  private init() {
    this.signalRService.subscribeToAnswer((answer, message) => this.toggle(answer, message));
    this.signalRService.subscribeToReceiveMessage((message) => this.setHost(message))
    this.signalRService.addToGroup(this.groupName);
  }

  private setHost(message: string) {
    this.toggle(Utils.STATE_ANSWER_NORMAL, message);
  }

  private toggle(answer: string, message: string) {
    this.setAnswerState(answer);
    this.resetOldAnswerState();

    switch (this.card1State) {
      case Utils.STATE_TRANSITION_ON: 
          this.card1State = Utils.STATE_TRANSITION_OFF;
          this.card2State = Utils.STATE_TRANSITION_ON;
          this.card2Message = message;
        break;

      case Utils.STATE_TRANSITION_OFF:
        this.card1State = Utils.STATE_TRANSITION_ON;
        this.card1Message = message;
        this.card2State = Utils.STATE_TRANSITION_OFF;
        break;

      default:
        break;
    }
  }

  private resetOldAnswerState() {
    if(this.card1State === Utils.STATE_TRANSITION_ON) {
      this.card2AnswerState = Utils.STATE_ANSWER_NORMAL;
    } else {
      this.card1AnswerState = Utils.STATE_ANSWER_NORMAL;
    }
  }
 
  private setAnswerState(anwserState: string) {
    if(this.card1State === Utils.STATE_TRANSITION_ON) {
      this.card1AnswerState = anwserState;
    } else {
      this.card2AnswerState = anwserState;
    }
  }
}

// BigScreenReact/BigScreenReact/ClientApp/src/components/Screen-Card.tsx
import React, {useEffect, useRef, useState} from 'react'
import Card from './Card';
import { IService, useService } from '../services/serviceContext';
import { Utils } from '../utils';
import NavigationService from '../services/navigation.service';

function ScreenCard() {
    const service = useService();
    let groupName: string;
  
    const [card1Message, setCard1Message] = useState("Welcome!");
    const [card2Message, setCard2Message] = useState("2");
    const [card1State, setCard1State] = useState(Utils.STATE_TRANSITION_ON);
    const [card2State, setCard2State] = useState(Utils.STATE_TRANSITION_OFF);
    const [card1AnswerState, setCard1AnswerState] = useState(Utils.STATE_ANSWER_NORMAL);
    const [card2AnswerState, setCard2AnswerState] = useState(Utils.STATE_ANSWER_NORMAL);

    useEffect(() => {
        service.subscribeToAnswer((answer, message) => toggle(answer, message));
        service.subscribeToReceiveMessage((message) => setHost(message))
        groupName = NavigationService.groupName;
        service.addToGroup(groupName);
    }, [])
    
    function setHost(message: string) {
        toggle(Utils.STATE_ANSWER_NORMAL, message);
    }
    
    function toggle(answer: string, message: string) {
        setAnswerState(answer);
        resetOldAnswerState();

        // switch (card1State) {
        //     case Utils.STATE_TRANSITION_ON: 
        //         setCard1State(Utils.STATE_TRANSITION_OFF);
        //         setCard2State(Utils.STATE_TRANSITION_ON);
        //         setCard2Message(message)
        //         break;

        //     case Utils.STATE_TRANSITION_OFF:
        //         setCard1State(Utils.STATE_TRANSITION_ON);
        //         setCard1Message(message)
        //         setCard2State(Utils.STATE_TRANSITION_OFF);
        //         break;

        //     default:
        //         break;
        // }

        setCard1Message(message);
    }
    
    function resetOldAnswerState() {
        if(card1State === Utils.STATE_TRANSITION_ON) {
            setCard2AnswerState(Utils.STATE_ANSWER_NORMAL);
        } else {
            setCard1AnswerState(Utils.STATE_ANSWER_NORMAL);
        }
    }
     
    function setAnswerState(anwserState: string) {
        if(card1State === Utils.STATE_TRANSITION_ON) {
            setCard1AnswerState(Utils.STATE_ANSWER_NORMAL);
        } else {
            setCard2AnswerState(Utils.STATE_ANSWER_NORMAL);
        }
    }

    return (
        <div className='grid-container'>
            <div className='grid'>
                <div className='card1'>
                    <Card cardMessage={card1Message} answerState={card1State}></Card>
                </div>
                {/* <div className='card2'>
                    <Card cardMessage={card2Message} answerState={card2State}></Card>
                </div> */}
            </div>
        </div>
    )
}

export default ScreenCard;
